name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Mostrar estrutura
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -type f

      - name: Gerar Wrapper
        run: |
          if [ ! -f gradlew ]; then
            gradle wrapper
          fi

      - name: Dar permissão
        run: chmod +x gradlew

      - name: Build Debug
        run: ./gradlew assembleDebug --stacktrace

      - name: Localizar APK
        run: find . -name "*.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GameBooster-APK
          path: app/build/outputs/apk/debug/*.apk
